package com.motsolutions.proco.gui;

import java.awt.event.ActionListener;
import javax.swing.JList;

/**
 * Please do not change this class - you should not need to change here anything, especially
 * that part of this code was auto-generated by the GUI designer. Modify the <tt>MainController</tt> instead.
 */
public class MainWindow extends javax.swing.JFrame {
	public MainWindow() {
		initComponents();
		this.setTitle("Producers and consumers GUI");
	}

	public JList getMagazineList() {
		return magazineList;
	}

	public JList getProducerList() {
		return producerList;
	}

	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jPanel1 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          magazineList = new javax.swing.JList<>();
          jPanel2 = new javax.swing.JPanel();
          jScrollPane2 = new javax.swing.JScrollPane();
          producerList = new javax.swing.JList<>();
          startAllButton = new javax.swing.JButton();
          stopAllButton = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Magazine"));

          magazineList.setModel(new javax.swing.AbstractListModel<String>() {
               String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
               public int getSize() { return strings.length; }
               public String getElementAt(int i) { return strings[i]; }
          });
          jScrollPane1.setViewportView(magazineList);

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1)
          );

          jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Producers"));

          producerList.setModel(new javax.swing.AbstractListModel<String>() {
               String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
               public int getSize() { return strings.length; }
               public String getElementAt(int i) { return strings[i]; }
          });
          jScrollPane2.setViewportView(producerList);

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane2)
          );

          startAllButton.setText("Start all");

          stopAllButton.setText("Stop all");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(layout.createSequentialGroup()
                              .addComponent(startAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(stopAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(startAllButton)
                         .addComponent(stopAllButton))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

	public void setStartAllAction(ActionListener listener) {
		this.startAllButton.addActionListener(listener);
	}

	public void setStopAllAction(ActionListener listener) {
		this.stopAllButton.addActionListener(listener);
	}

	public void initializeButtonStateListeners(boolean initiallyStarted) {
		startAllButton.setEnabled(!initiallyStarted);
		stopAllButton.setEnabled(initiallyStarted);
		this.startAllButton.addActionListener((evt) -> {
			startAllButton.setEnabled(false);
			stopAllButton.setEnabled(true);
		});
		this.stopAllButton.addActionListener((evt) -> {
			startAllButton.setEnabled(true);
			stopAllButton.setEnabled(false);
		});
	}

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JList<String> magazineList;
     private javax.swing.JList<String> producerList;
     private javax.swing.JButton startAllButton;
     private javax.swing.JButton stopAllButton;
     // End of variables declaration//GEN-END:variables
}
